config/routes.rb
Tripster::Application.routes.draw do

  resources :trips do
    resources :pictures, :only => [:new, :create, :edit, :update, :show, :destroy]
  end

  resources :points, only: [] do
      resources :pictures, :only => [:new, :create, :edit, :update, :show, :destroy]
  end

  resource :user_sessions, :only => [:new, :create, :destroy]

  resources :users, :only => [:new, :create, :edit, :update, :index, :show, :destroy] do
    get 'edit_avatar', :on => :member
    put 'update_avatar', :on => :member
  end

  root :to => "trips#index"

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :pictures, :as => :imageable, :dependent => :destroy
  has_many :points, :dependent => :destroy
  accepts_nested_attributes_for :points, :allow_destroy => true

  validates :name, :presence => true
  validates :description, :presence => true

  attr_accessible :name, :description, :points_attributes
end

app/controllers/trips_controller.rb
# encoding: utf-8
class TripsController < ApplicationController
  before_filter :authenticate, :only => [:new, :edit, :destroy]
  before_filter :admin_required, :only => [:destroy]

  def index
    @trips = Trip.order('created_at desc').page(params[:page]).per(5)
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(params[:trip])
    @trip.user = current_user
    if @trip.save
      flash[:success] = "Podróż została utworzona!"
      redirect_to @trip
    else
      render :action => 'new'
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update_attributes(params[:trip])
      flash[:success] = "Poprawnie zaaktualizowano podróż."
      redirect_to @trip
    else
        render :action => 'edit'
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    flash[:info] = "Usunięto podróż."
    redirect_to trips_path
  end
end

app/helpers/trips_helper.rb
module TripsHelper
  def link_to_new_point(name, f)
    html = render :partial => 'trips/point', :locals => {
        :object => Point.new, :index => 'to_replace', :f => f, :delete => true }
    link_to_function name, %{
      var new_object_id = new Date().getTime();
      var html = '#{escape_javascript html}'.replace(/to_replace/g, new_object_id);
      $('#points').append(html);
      addMarker("trip_points_attributes_" + new_object_id);
    }
  end

  def map_tag(lat, lng, options = {})
    sensor = options[:sensor] || false
    size   = options[:size] || "200x200"
    zoom   = options[:zoom] || 11
    image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{lat},#{lng}&zoom=#{zoom}&size=#{size}&sensor=#{sensor}"
  end
end

app/views/trips/_form.html.erb
<% content_for :head do %>
    <%= javascript_include_tag '//maps.googleapis.com/maps/api/js?sensor=false' %>
    <script type="text/javascript">
          var stockholm = new google.maps.LatLng(59.32522, 18.07002);
          var parliament = new google.maps.LatLng(59.327383, 18.06747);
          var markers = [];
          var map;

          function map() {
            var mapOptions = {
              zoom: 13,
              mapTypeId: google.maps.MapTypeId.ROADMAP,
              center: stockholm
            };
            map = new google.maps.Map(document.getElementById("map"),
                    mapOptions);
          }

          function addMarker(id, lat, lng) {
            var position = map.getCenter();
            if (lat != null && lng != null) {
                position = new google.maps.LatLng(lat, lng);
            }
            var marker = new google.maps.Marker({
              map: map,
              draggable: true,
              animation: google.maps.Animation.DROP,
              position: position
            });
            marker.id = id;
            $('#' + id + '_lat').val(marker.getPosition().lat());
            $('#' + id + '_lng').val(marker.getPosition().lng());
            google.maps.event.addListener(marker, 'dragend', function() {
                $('#' + this.id + '_lat').val(marker.getPosition().lat());
                $('#' + this.id + '_lng').val(marker.getPosition().lng());
            });
            markers.push(marker);
          }

          function removeMarker(id) {
            for(index in markers) {
                var marker = markers[index];
                if(marker.id == id) {
                    marker.setMap(null);
                }
            }
          }
    </script>
<% end %>

<div id="trip-new">
  <div id="trip-form">
    <% unless f.object.errors.empty? %>
    <ul class="errors">
      <% f.object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
    <div class="field">
      <%= f.label :name, 'Nazwa' %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description, 'Opis' %>
      <%= f.text_area :description, :style => 'height: 150px; width: 350px' %>
    </div>
  </div>
  <div id="map">
    map
  </div>
  <div class="clear"></div>
  <h2>Punkty</h2>
  <div id="points">
    <% f.object.points.each_with_index do |point, index| %>
        <%= render :partial => 'trips/point', :locals => { :f => f, :object => point, :index => index } %>
    <% end %>
  </div>
  <div id="point-new">
    <%= link_to_new_point 'Dodaj punkt', f %>
  </div>
  <div style="text-align: center"><%= f.submit('Zapisz', :class => 'btn btn-large btn-success') %></div>
</div>

app/views/trips/_point.html.erb
<div class='point'>
  <%= f.fields_for :points, object, :child_index => index do |fields| %>
    <%= fields.hidden_field :lat %>
    <%= fields.hidden_field :lng %>
    <div class='field'>
      <%= fields.label :name, 'Nazwa punktu' %>
      <%= fields.text_field :name %>
    </div>
    <div class='field'>
      <%= fields.label :description, 'Opis' %>
      <%= fields.text_area :description, :style => 'height: 100px; width: 500px' %>
    </div>
    <% unless object.new_record? %>
    <div class='field'>
      <%= fields.check_box :_destroy %>
      <%= fields.label :_destroy, 'Usuń punkt' %>
      lub
      <%= link_to_function 'Pokaż na mapie', %{ map.setCenter(new google.maps.LatLng(#{object.lat}, #{object.lng}))
        } %> <!-- Wcześniej była tu funkcja (ale w ogóle nie działała): addMarker("trip_points_attributes_#{index}", #{object.lat}, #{object.lng}); teraz jest to, ale nie wyświetla punktu, tylko centruje na niego mapę. -->
    </div>
    <% end %>

  <% end %>
  <% if object.new_record? %>
    <div class='links'>
      <%= link_to_function 'Usuń', "$(this).parent().parent().remove(); removeMarker('trip_points_attributes_#{index}')" %>
    </div>
  <% end %>
  <% javascript_tag do %>
    addMarker("trip_points_attributes_<%= index %>");
  <% end %>
</div>

app/views/trips/edit.html.erb
<h1><%= link_to @trip.name, @trip %> (edycja)</h1>
<%= form_for @trip do |f| %>
    <%= render :partial => "trips/form", :locals => { :f => f } %>
<% end %>

app/views/trips/index.html.erb
<ul class="nav nav-pills big">
  <li class="active"><%= link_to 'Podróże', trips_path %></li>
  <li class><%= link_to 'Tripsterzy', users_path %></li>
  <span class="pull-right">
  <%= link_to('Dodaj podróż', new_trip_path, :class => "btn btn-success btn-large") %>
  </span>
</ul>
<% if flash[:error] %>
<div class="alert alert-error">
  <%= flash[:error] %>
  <%= link_to '×', root_url, :class => "close" %>
</div>
<% end %>
<% if flash[:info] %>
<div class="alert alert-info">
  <%= flash[:info] %>
  <%= link_to '×', root_url, :class => "close" %>
</div>
<% end %>
<% if flash[:success] %>
<div class="alert alert-success">
  <%= flash[:success] %>
  <%= link_to '×', root_url, :class => "close" %>
</div>
<% end %>
<div id="trips">
  <% @trips.all.each do |trip| %>
  <div id="trip-<%= trip.id %>" class="trip">
    <div class="map">
      <% unless trip.points.empty? %>
        <%= map_tag trip.points.first.lat, trip.points.first.lng, :size => '400x200' %>
      <% else %>
        <% unless current_user && current_user == trip.user %>
        <%= image_tag("400x200.jpg", :alt => "Nie dodano punktów podróży", :title => "Nie dodano punktów podróży") %>
        <% else %>
        <%= link_to image_tag("400x200.jpg", :alt => "Nie dodano punktów podróży", :title => "Nie dodano punktów podróży"), edit_trip_path(trip) %>
        <% end %>
      <% end %>
    </div>
    <div class="details">
        <h3><%= trip.name %></h3>
        <div><%= link_to trip.user.login, trip.user %></div>
        <div class="description">
          <%= truncate(trip.description, :length => 395, :omission => '...') %>
        </div>
        <div class="links">
          <i><%= link_to 'Więcej...', trip %></i>
          <% if current_user && current_user.admin? %>
            &middot;
            <%= link_to 'Edytuj', edit_trip_path(trip) %>
            &middot;
            <%= link_to 'Usuń', trip, :method => :delete, :confirm => 'Na pewno chcesz usunąć?' %>
          <% end %>
        </div>
      </div>
      <div class="next"></div>
  </div>
  <% end %>
</div>
<%= paginate @trips %>

app/views/trips/new.html.erb
<h1>Dodaj podróż</h1>

<%= form_for @trip do |f| %>
    <%= render :partial => "trips/form", :locals => { :f => f } %>
<% end %>

app/views/trips/show.html.erb
<% content_for :head do %>
    <% unless @trip.points.empty? %>
      <%= javascript_include_tag '//maps.googleapis.com/maps/api/js?sensor=false' %>
      <%= javascript_tag do %>
            var markers = [];
            var map;

            function map() {
              var first = new google.maps.LatLng(<%= @trip.points.first.lat %>, <%= @trip.points.first.lng %>);
              var mapOptions = {
                zoom: 13,
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                center: first
              };
              map = new google.maps.Map(document.getElementById("map"),
                      mapOptions);
            <% @trip.points.all.each do |point| %>
              new google.maps.Marker({
                map: map,
                draggable: true,
                animation: google.maps.Animation.DROP,
                position: new google.maps.LatLng(<%= point.lat %>, <%= point.lng %>)
              });
            <% end %>
            }
      <% end %>
    <% end %>
<% end %>
<div id="wrapper">
  <% if flash[:error] %>
  <div class="alert alert-error">
    <%= flash[:error] %>
    <%= link_to '×', trip_path(@trip), :class => "close" %>
  </div>
  <% end %>
  <% if flash[:info] %>
  <div class="alert alert-info">
    <%= flash[:info] %>
    <%= link_to '×', trip_path(@trip), :class => "close" %>
  </div>
  <% end %>
  <% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:success] %>
    <%= link_to '×', trip_path(@trip), :class => "close" %>
  </div>
  <% end %>
  <% if current_user && (current_user.admin? || current_user == @trip.user) %>
  <span class="pull-right">
    <%= link_to image_tag("edit.svg", :size => "32x32", :title => "Edytuj podróż", :alt => "Edytuj podróż"), edit_trip_path(@trip) %>
    <%= link_to image_tag("delete.svg", :size => "32x32", :title => "Usuń podróż", :alt => "Usuń podróż"), @trip, :method => :delete, :confirm => 'Na pewno chcesz usunąć podróż?' %>
  </span>
  <% end %>
  <h1><%= @trip.name %></h1>
  <h3>autor: <%= link_to @trip.user.login, @trip.user %></h3>
  <div class="description">
    <%= simple_format(@trip.description) %>
  </div>
  <% unless @trip.points.empty? %>
    <div id="map" style="width: 99%; height: 200px; margin-bottom: 15px;">
      Map
    </div>
  <% end %>
  <% if current_user && current_user==@trip.user %>
    <p><%= link_to('Dodaj zdjęcie do podróży', new_trip_picture_path(@trip), :class => "btn btn-large") %></p>
  <% end %>
  <% unless @trip.pictures.empty? %>
  <!-- Wyświetlenie miniaturek zdjęć z podróży -->
    <ul class="thumbnails">
      <% @trip.pictures.each do |picture| %>
        <li class="span2">
            <%= link_to image_tag(picture.image_url(:thumb).to_s, :title => '', :alt => ''), trip_picture_path(@trip.id, picture.id), :class => 'thumbnail' %>
          <% if current_user && current_user==@trip.user %>
          <div class="center thumblinks">
            <%= link_to 'Zmień', edit_trip_picture_path(@trip.id, picture.id) %>&nbsp;&middot;
            <%= link_to 'Usuń', trip_picture_path(@trip.id, picture.id), :confirm => 'Na pewno chcesz usunąć zdjęcie?', :method => :delete %>
          </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <% unless @trip.points.empty? %>
    <h3>Punkty podróży</h3>
    <div id="points">
      <% @trip.points.each do |point| %>
      <div class="point" id="point-<%= point.id %>">
        <div class="spaced">
          <h4 class="nextto"><%= point.name %></h4>
          <%= link_to_function 'Wskaż na mapie', %{ map.setCenter(new google.maps.LatLng(#{point.lat}, #{point.lng})) } %>
        </div>
        <% unless point.description.empty? %>
        <div class="description"><%= simple_format(point.description) %></div>
        <% end %>
        <% if current_user && current_user==@trip.user %>
          <p><%= link_to('Dodaj zdjęcie dla punktu', new_point_picture_path(point), :class => "btn btn-small") %></p>
        <% end %>
        <% unless point.pictures.empty? %>
        <!-- Wyświetlenie miniaturek zdjęć z poszczególnych punktów -->
          <ul class="thumbnails">
            <% point.pictures.each do |picture| %>
              <li class="span2">
                <%= link_to image_tag(picture.image_url(:thumb).to_s, :title => '', :alt => ''), point_picture_path(point.id, picture.id), :class => 'thumbnail' %>
                <% if current_user && current_user==@trip.user %>
                <div class="center thumblinks">
                  <%= link_to 'Zmień', edit_point_picture_path(point.id, picture.id) %>&nbsp;&middot;
                  <%= link_to 'Usuń', point_picture_path(point.id, picture.id), :confirm => 'Na pewno chcesz usunąć zdjęcie?', :method => :delete %>
                </div>
                <% end %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <% end %>
    </div>
  <% end %>
  <%= link_to 'Wszystkie podróże', trips_path %>&nbsp;&middot;&nbsp;<%= link_to 'Profil autora', @trip.user %>
</div>