config/routes.rb
Tripster::Application.routes.draw do

  resources :trips do
    resources :pictures, :only => [:new, :create, :edit, :update, :show, :destroy]
  end

  resources :points, only: [] do
      resources :pictures, :only => [:new, :create, :edit, :update, :show, :destroy]
  end

  resource :user_sessions, :only => [:new, :create, :destroy]

  resources :users, :only => [:new, :create, :edit, :update, :index, :show, :destroy] do
    get 'edit_avatar', :on => :member
    put 'update_avatar', :on => :member
  end

  root :to => "trips#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_protected :admin
  acts_as_authentic do |config|
    config.crypted_password_field = :crypted_password
    config.require_password_confirmation = true
    config.validate_email_field = false
  end
  strip_attributes :except => [:password, :password_confirmation]
  validates :email, :allow_blank => true,
                    :length => {:minimum => 3, :maximum => 254},
                    :uniqueness => true,
                    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
  validates :bio, :allow_blank => true,
                  :length => { :maximum => 140}
  mount_uploader :avatar, ImageUploader
  has_many :trips, :dependent => :destroy
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController

  before_filter :authenticate, :only => [:edit, :edit_avatar]
  before_filter :admin_required, :only => [:delete]

  # GET /users
  def index
    @users = User.order('created_at asc').page(params[:page]).per(12)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Pomyślnie zarejestrowano konto."
      redirect_to @user
    else
      render :action => 'new'
    end
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
    @trips = @user.trips.order('created_at desc').page(params[:page]).per(5)
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    unless current_user && (current_user == @user or current_user.admin?)
      flash[:error] = "Próbujesz wykonać niedozwoloną akcję. Nieładnie."
      redirect_to root_url
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Zapisano zmiany."
      redirect_to user_path(@user.id)
    else
      render :action => 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:info] = "Usunięto użytkownika."
    redirect_to users_url
  end

  # GET /users/1/edit_avatar
  def edit_avatar
    @user = User.find(params[:id])
    unless current_user && (current_user == @user or current_user.admin?)
      flash[:error] = "Próbujesz wykonać niedozwoloną akcję. Nieładnie."
      redirect_to root_url
    end
  end

  def update_avatar
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Pomyślnie zmieniono awatar."
      redirect_to user_path(@user.id)
    else
      render :action => 'edit_avatar'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="row">
<div class="span6 offset4">
  <h2>Edycja profilu</h2>
  <%= form_for @user do |f| %>
  <!-- komunikaty błędów -->
  <% if @user.errors.any? %>
  <ul class="errors">
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %> </li>
  <% end %>
  </ul>
  <% end %>
  <div class="field">
    <%= f.label :fullname, "Pełne imię:" %>
    <%= f.text_field(:fullname, :class => "input-xlarge", :size => "30") %>
  </div>
  <div class="field">
    <%= f.label :email, "E-mail:" %>
    <%= f.text_field(:email, :class => "input-xlarge", :size => "30") %>
  </div>
  <div class="field">
  <%= f.label :bio, "O mnie:" %>
  <%= f.text_area(:bio, :rows => "3") %>
  </div>
  <div class="field">
  <%= f.label :location, "Miejsce pobytu:" %>
  <%= f.text_field(:location, :class => "input-xlarge", :size => "30") %>
  </div>
  <h3>Zmiana hasła</h3>
  <p><span class="label label-info">nie wpisuj nic w tej sekcji, jeśli nie chcesz zmieniać hasła.</span></p></center>
  <div class="field">
  <%= f.label :password, "Nowe hasło:" %>
  <%= f.password_field(:password, :class => "input-xlarge", :size => "30") %>
  </div>
  <div class="field">
  <%= f.label :password_confirmation, "Potwierdź nowe hasło:" %>
  <%= f.password_field(:password_confirmation, :class => "input-xlarge", :size => "30") %>
  </div>
  <div class="actions"><%= f.submit('Zapisz zmiany', :class => "btn btn-large btn-primary" ) %>
  <%= link_to('Powrót', @user, :class => "btn btn-large nextto" ) %></div>

  <% end %>
</fieldset>
</div>
</div>

app/views/users/edit_avatar.html.erb
<div id="smallform" class="center centered">
  <h2>Twój awatar</h2>
  <%= form_for @user, :url => update_avatar_user_path(@user), :html => {:multipart => true} do |f| %>
    <!-- komunikaty błędów -->
    <% if @user.errors.any? %>
    <ul class="errors">
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %> </li>
      <% end %>
    </ul>
    <% end %>
      <div class="spaced well avatar">
      <%= image_tag(@user.avatar_url(:thumb)) if @user.avatar?%>
      <% unless @user.avatar? %>
      Nie wybrałeś jeszcze awatara, używasz domyślnego.
      <% end %>
      </div>
      <p><%= f.file_field :avatar %></p>
      <%= f.hidden_field :avatar_cache %>
    <p><%= f.submit('Zapisz', :class => "btn") %></p>
  <% end %>

</div>

app/views/users/index.html.erb
<ul class="nav nav-pills big">
  <li class><%= link_to 'Podróże', trips_path %></li>
  <li class="active"><%= link_to 'Tripsterzy', users_path %></li>
  <span class="pull-right">
    <%= link_to('Dodaj podróż', new_trip_path, :class => "btn btn-success btn-large") %>
  </span>
</ul>
<% if flash[:error] %>
<div class="alert alert-error">
  <%= flash[:error] %>
  <%= link_to '×', users_path, :class => "close" %>
</div>
<% end %>
<% if flash[:info] %>
<div class="alert alert-info">
  <%= flash[:info] %>
  <%= link_to '×', users_path, :class => "close" %>
</div>
<% end %>
<% if flash[:success] %>
<div class="alert alert-success">
  <%= flash[:success] %>
  <%= link_to '×', users_path, :class => "close" %>
</div>
<% end %>
<div id="users">
  <div class="user row">
  <% @users.each_with_index do |user, i| %>
    <div class="span4">
      <div class="span2">
      <% if user.avatar? %>
      <%= link_to image_tag(user.avatar_url(:thumb).to_s, :title => "Awatar użytkownika #{user['login']}", :alt => "Awatar użytkownika #{user['login']}"), user_path(user.id) %>
      <% else %>
        <%= image_tag("/assets/default_avatar.jpg", :title => "Defaultowy awatar", :alt => "Defaultowy awatar") %>
      <% end %>
      </div>
      <div class="span2 about">
        <h3 class="nextto"><%= link_to "#{user['login']}", user_path(user.id) %></h3>
        <% unless user.fullname.nil? || user.fullname.empty? %>
          <div><h4><%= user.fullname %></h4></div>
        <% end %>
        <% unless user.location.nil? || user.location.empty? %>
          <div><%= user.location %></div>
        <% end %>
      </div>
    </div>
    <% if (i+1)%3 == 0 %>
  </div>
  <div class="user row">
    <% end %>
  <% end %>
  </div>
</div>
<%= paginate @users %>

app/views/users/new.html.erb
<div class="row">
<div class="span4 offset4">
  <%= form_for @user do |f| %>
    <h2>Dołącz do nas!</h2>
    <!-- komunikaty błędów -->
    <% if @user.errors.any? %>
    <ul class=errors>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %> </li>
    <% end %>
    </ul>
    <% end %>
    <div class="field">
    <%= f.label :login, "Login:" %>
    <%= f.text_field :login, {:class => "input-xlarge"} %>
    <p class="help-block">Pole wymagane.</p>
    </div>
    <div class="field">
    <%= f.label :password, "Hasło:" %>
    <%= f.password_field :password, {:class => "input-xlarge"} %>
    <p class="help-block">Pole wymagane.</p>
    </div>
    <div class="field">
    <%= f.label :password_confirmation, "Potwierdź hasło:" %>
    <%= f.password_field :password_confirmation, {:class => "input-xlarge"} %>
    <p class="help-block">Pole wymagane.</p>
    </div>
    <div class="field">
    <%= f.label :fullname, "Pełne imię:" %>
    <%= f.text_field :fullname, {:class => "input-xlarge"} %>
    <p class="help-block">Pole opcjonalne. Możesz uzupełnić je później.</p>
    </div>
    <div class="field">
    <%= f.label :email, "E-mail:" %>
    <%= f.text_field :email, {:class => "input-xlarge"} %>
    <p class="help-block">Pole opcjonalne. Możesz uzupełnić je później.</p>
    </div>

    <div class="form-actions">
    <%= f.submit("Stwórz konto!", :class => "btn btn-large btn-primary") %>
    </div>


  <% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="span12">
    <div class="user-header">
      <h1 class="nextto"><%= link_to "#{@user['login']}", user_path(@user.id) %>
      <small>
        <% if current_user && current_user==@user %>
        Twój profil
        <% else %>
        Profil
        <% end %>
      </small>
      </h1>
      <% if current_user && current_user==@user %>
      <span class="pull-right">
        <%= link_to('Dodaj podróż', new_trip_path, :class => "btn btn-success btn-large") %>
      </span>
      <% end %>
    </div>
  </div>
</div>
<div class="row showuser">
  <div class="span3 side">
    <% if @user.avatar? %>
      <%= image_tag(@user.avatar_url(:thumb).to_s, :title => "Awatar użytkownika #{@user['login']}", :alt => "Awatar użytkownika #{@user['login']}") %>
    <% else %>
      <%= image_tag("/assets/default_avatar.jpg", :title => "Defaultowy awatar", :alt => "Defaultowy awatar") %>
    <% end %>
    <% if current_user && current_user==@user %>
      <div><%= link_to('Zmień obrazek profilowy', edit_avatar_user_path(@user), :class => "btn btn-small") %></div>
    <% end %>
    <div class="userinfo">
      <% unless @user.fullname.nil? || @user.fullname.empty? %>
        <div><h4><%= @user.fullname %></h4></div>
      <% end %>
      <% unless @user.email.nil? || @user.email.empty? %>
        <div><%= @user.email %></div>
      <% end %>
      <% unless @user.location.nil? || @user.location.empty? %>
        <div><%= @user.location %></div>
      <% end %>
      <% unless @user.bio.nil? || @user.bio.empty? %>
        <div><i><%= simple_format(@user.bio) %></i></div>
      <% end %>
    </div>
    <br />
    <% if current_user %>
      <% if current_user==@user || current_user.admin? %>
      <%= link_to 'Edytuj profil', edit_user_path(@user) %>
      <% end %>
      <% if current_user.admin? && current_user!=@user %>
      &middot;&nbsp;<%= link_to 'Usuń użytkownika', @user, :confirm => "Na pewno chcesz usunąć użytkownika?", :method => :delete %>
      <% end %>
    <br /><br />
    <% end %>
    <div><%= link_to 'Tripsterzy', users_path %></div>
    <div><%= link_to 'Podróże', trips_path %></div>
  </div>
  <div class="span9">
    <% if flash[:error] %>
    <div class="alert alert-error">
      <%= flash[:error] %>
      <%= link_to '×', user_path(@user), :class => "close" %>
    </div>
    <% end %>
    <% if flash[:info] %>
    <div class="alert alert-info">
      <%= flash[:info] %>
      <%= link_to '×', user_path(@user), :class => "close" %>
    </div>
    <% end %>
    <% if flash[:success] %>
    <div class="alert alert-success">
      <%= flash[:success] %>
      <%= link_to '×', user_path(@user), :class => "close" %>
    </div>
    <% end %>
    <% unless @trips.empty? %>
      <% @trips.each do |trip| %>
      <div id="trip-<%= trip.id %>" class="row trip-small">
        <div class="span4 map">
          <% unless trip.points.empty? %>
            <%= map_tag trip.points.first.lat, trip.points.first.lng, :size => '400x200' %>
          <% else %>
            <% unless current_user && current_user == trip.user %>
            <%= image_tag("400x200.jpg", :alt => "Nie dodano punktów podróży", :title => "Nie dodano punktów podróży") %>
            <% else %>
            <%= link_to image_tag("400x200.jpg", :alt => "Nie dodano punktów podróży", :title => "Nie dodano punktów podróży"), edit_trip_path(trip) %>
            <% end %>
          <% end %>
        </div>
        <div class="span5 details">
          <h3><%= trip.name %></h3>
          <div><%= link_to trip.user.login, trip.user %></div>
          <div class="description-small">
            <%= truncate(trip.description, :length => 235, :omission => '...') %>
          </div>
          <div class="links">
            <i><%= link_to 'Więcej...', trip %></i>
            <% if current_user && current_user.admin? %>
              &middot;
              <%= link_to 'Edytuj', edit_trip_path(trip) %>
              &middot;
              <%= link_to 'Usuń', trip, :method => :delete, :confirm => 'Na pewno chcesz usunąć?' %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
      <%= paginate @trips %>
    <% else %>
    <h1><small>Nie dodano jeszcze żadnej podróży.</small></h1>
    <% end %>
  </div>
</div>