config/routes.rb
Tripster::Application.routes.draw do

  resources :trips do
    resources :pictures, :only => [:new, :create, :edit, :update, :show, :destroy]
  end

  resources :points, only: [] do
      resources :pictures, :only => [:new, :create, :edit, :update, :show, :destroy]
  end

  resource :user_sessions, :only => [:new, :create, :destroy]

  resources :users, :only => [:new, :create, :edit, :update, :index, :show, :destroy] do
    get 'edit_avatar', :on => :member
    put 'update_avatar', :on => :member
  end

  root :to => "trips#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Tripster</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style type="text/css">
  /* Override some defaults */
  html, body {
  background-color: #eee;
  }

  body {
  padding-top: 50px; /* 50px to make the container go all the way to the bottom of the topbar */
  }

  .container > footer p {
  text-align: center; /* center align it with the container */
  color: #D4D4D4;
  padding-top: 15px;
  }

  .navbar-inner > .container {
    width: 960px;
  }

  .navbar .brand {
    font-weight: bold;
    font-size: 28px;
    padding-top: 10px;
    padding-left: 22px;
  }

  .navbar .nav { margin: 0; }

  .navbar .nav > li > a {
    padding: 15px 10px 11px;
    color: #F2F2F2;
  }
  .navbar .nav > li > a:hover {
    color: #FAE098;
  }

  /* The white background content wrapper */
  .content {
  min-height: 300px;
  background-color: #fff;
  padding: 20px;
  margin: 0 -20px; /* negative indent the amount of the padding to maintain the grid system */
  -webkit-border-radius: 0 0 6px 6px;
     -moz-border-radius: 0 0 6px 6px;
          border-radius: 0 0 6px 6px;
  -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
     -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
          box-shadow: 0 1px 2px rgba(0,0,0,.15);
  }

  </style>
  <%= yield :head %>
</head>
<body onload="if(typeof map == 'function') { map() }">
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= image_tag('globe.png', :title => 'tripster logo', :alt => 'tripster logo', :size =>'32x32', :class => 'pull-left logo') %>
        <%= link_to 'tripster', root_url, :class => 'brand' %>
        <div class="pull-right">
          <ul class="nav">
          <% unless current_user %>
          <li class><%= link_to "Zarejestruj się", new_user_path %></li>
          <li class><%= link_to "Zaloguj", new_user_sessions_path %></li>
          <% end %>
          <% unless current_user.nil? %>
          <li class="loggedas">Zalogowany/a jako</li>
          <li class><%= link_to "#{current_user['login']}", user_path(current_user.id), :class => 'usr' %></li>
          <li class><%= link_to "Wyloguj", user_sessions_path, :method => :delete, :class => 'logout' %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="content">
      <%= yield %>
    </div> <!-- /content -->
    <footer>
        <p>&copy; Barbara Żądło &amp; Julia Jacobs 2012</p>
    </footer>
  </div>  <!-- /container -->
</body>
</html>